server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8 

spring:
  application:
    name: cict-offical-network
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/news.db #数据库，在resources目录创建了资源文件夹db，根据实际情况指定
    username: news
    password: news
  jpa:
    database-platform: com.cict.offical.network.base.SQLiteDialect
    hibernate:
      ddl-auto: update      
    generate-ddl: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    
matcherPath: /hello



